version: '2.4'
services:
  py:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:11-alpine
    environment:
      # Super-User: by default POSTGRES_USER="postgres"
      - "POSTGRES_DB=${POSTGRES_DB}"
      #      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    #restart: always
#    volumes:
#      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
